import {
  project1_1,
  project1_2,
  project2_1,
  project2_2,
  project3_1,
  project3_2,
  // project3Laptop,
  // project3Mobile,
  // project4Laptop,
  // project4Mobile,
  // project5Laptop,
  // project5Mobile,
  // project6Laptop,
  // project6Mobile,
  
} from "./projectImages";

export const projectData = [
  {
    id: 1,
    image: project1_1,
    transitionImage: project1_2,
    title: "Lately Clone",
    description:"This is a clone of 'Lately' Lately is an AI-powered social media marketing platform that helps marketers scale their publishing and reach. In this website I have implemented some functionalities like login & signup user data authentication etc. ",
    techStack:"React | Redux | JavaScript | Chakra UI ",
    codeLink: "https://github.com/Hisam-94/-plastic-stone-9805/tree/main/Lately-Clone",
    liveLink: "https://hisamuddin-lately-clone.netlify.app/",
  },
  {
    id: 2,
    image: project2_1,
    transitionImage: project2_2,
    title: "ESPN Cricinfo Clone",
    description:"This is a clone of 'ESPN Cricinfo' In which I have implemented some functionalities like login & signup user data authentication, Live matches score, Ongoing matches, Upcoming    matches schedule, Match results, Sports news etc.",
    techStack:"HTML | CSS | JavaScript | Bootstrap",
    codeLink: "https://github.com/vivek13420/CricInfo-Clone",
    liveLink: "https://unique-sopapillas-d61969.netlify.app/",
  },
  {
    id: 3,
    image: project3_1,
    transitionImage: project3_2,
    title: "Monsterindia Clone",
    description:"This is a clone of 'Monsterindia' In which I have tried to implemet functionalities like User Sign-in/ Sign-up, User authentication and validation. Built Job Search section and Advance Job Search section of the website. etc.",
    techStack:"HTML | CSS | JavaScript | Bootstrap ",
    codeLink: "https://github.com/Chandan-Mourya/MonsterindiaClone",
    liveLink: "https://chandan-mourya-monsterindiaclone.netlify.app/",
  },
  // {
  //   id: 4,
  //   image: project4Laptop,
  //   transitionImage: project4Mobile,
  //   title: "IT Company",
  //   codeLink: "https://github.com/monciego/coderig-landing-page",
  //   liveLink: "https://codeegrid.netlify.app/",
  // },
  // {
  //   id: 5,
  //   image: project5Laptop,
  //   transitionImage: project5Mobile,
  //   title: "Gym Fitness Website",
  //   codeLink: "https://github.com/monciego/intrepide",
  //   liveLink: "https://intrepide.netlify.app/",
  // },
  // {
  //   id: 6,
  //   image: project6Laptop,
  //   transitionImage: project6Mobile,
  //   title: "Space Tourism",
  //   codeLink: "https://github.com/monciego/space-tourism",
  //   liveLink: "https://spacetourism-monciego.netlify.app/",
  // },
];
